version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B package --file pom.xml
workflows:
  build:
    jobs:
      - build
